#include <stdio.h>
#include <stdlib.h>

char *deviceDescriptionXML(const char *deviceName, const char *deviceUUID) {
  const char *format =
      "<?xml version=\"1.0\"?>\n"
      "<root xmlns=\"urn:schemas-upnp-org:device-1-0\">\n"
      "  <specVersion><major>1</major><minor>0</minor></specVersion>\n"
      "  <device>\n"
      "    "
      "<deviceType>urn:schemas-upnp-org:device:MediaRenderer:1</deviceType>\n"
      "    <friendlyName>%s</friendlyName>\n"
      "    <manufacturer>go-dlna</manufacturer>\n"
      "    <modelName>mpv-renderer</modelName>\n"
      "    <UDN>%s</UDN>\n"
      "    <serviceList>\n"
      "      <service>\n"
      "        "
      "<serviceType>urn:schemas-upnp-org:service:AVTransport:1</serviceType>\n"
      "        <serviceId>urn:upnp-org:serviceId:AVTransport</serviceId>\n"
      "        <controlURL>/ctrl/avt</controlURL>\n"
      "        <eventSubURL>/evt/avt</eventSubURL>\n"
      "        <SCPDURL>/scpd/avt</SCPDURL>\n"
      "      </service>\n"
      "      <service>\n"
      "        "
      "<serviceType>urn:schemas-upnp-org:service:RenderingControl:1</"
      "serviceType>\n"
      "        <serviceId>urn:upnp-org:serviceId:RenderingControl</serviceId>\n"
      "        <controlURL>/ctrl/rc</controlURL>\n"
      "        <eventSubURL>/evt/rc</eventSubURL>\n"
      "        <SCPDURL>/scpd/rc</SCPDURL>\n"
      "      </service>\n"
      "      <service>\n"
      "        "
      "<serviceType>urn:schemas-upnp-org:service:ConnectionManager:1</"
      "serviceType>\n"
      "        "
      "<serviceId>urn:upnp-org:serviceId:ConnectionManager</serviceId>\n"
      "        <controlURL>/ctrl/cm</controlURL>\n"
      "        <eventSubURL>/evt/cm</eventSubURL>\n"
      "        <SCPDURL>/scpd/cm</SCPDURL>\n"
      "      </service>\n"
      "    </serviceList>\n"
      "  </device>\n"
      "</root>";

  int size = snprintf(NULL, 0, format, deviceName, deviceUUID);

  char *xml = malloc(size + 1);
  if (xml == NULL) {
    return NULL;
  }

  snprintf(xml, size + 1, format, deviceName, deviceUUID);

  return xml;
}

const char* avtSCPDXML() {
    return "<?xml version=\"1.0\"?>\n"
           "<scpd xmlns=\"urn:schemas-upnp-org:service-1-0\">\n"
           "  <specVersion><major>1</major><minor>0</minor></specVersion>\n"
           "  <actionList>\n"
           "    <action><name>SetAVTransportURI</name>\n"
           "      <argumentList>\n"
           "        <argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>\n"
           "        <argument><name>CurrentURI</name><direction>in</direction><relatedStateVariable>AVTransportURI</relatedStateVariable></argument>\n"
           "        <argument><name>CurrentURIMetaData</name><direction>in</direction><relatedStateVariable>AVTransportURIMetaData</relatedStateVariable></argument>\n"
           "      </argumentList>\n"
           "    </action>\n"
           "    <action><name>SetNextAVTransportURI</name>\n"
           "      <argumentList>\n"
           "        <argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>\n"
           "        <argument><name>NextURI</name><direction>in</direction><relatedStateVariable>NextAVTransportURI</relatedStateVariable></argument>\n"
           "        <argument><name>NextURIMetaData</name><direction>in</direction><relatedStateVariable>NextAVTransportURIMetaData</relatedStateVariable></argument>\n"
           "      </argumentList>\n"
           "    </action>\n"
           "    <action><name>Play</name>\n"
           "      <argumentList>\n"
           "        <argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>\n"
           "        <argument><name>Speed</name><direction>in</direction><relatedStateVariable>TransportPlaySpeed</relatedStateVariable></argument>\n"
           "      </argumentList>\n"
           "    </action>\n"
           "    <action><name>Stop</name>\n"
           "      <argumentList>\n"
           "        <argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>\n"
           "      </argumentList>\n"
           "    </action>\n"
           "    <action><name>Pause</name>\n"
           "      <argumentList>\n"
           "        <argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>\n"
           "      </argumentList>\n"
           "    </action>\n"
           "    <action><name>Next</name>\n"
           "      <argumentList>\n"
           "        <argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>\n"
           "      </argumentList>\n"
           "    </action>\n"
           "    <action><name>Previous</name>\n"
           "      <argumentList>\n"
           "        <argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>\n"
           "      </argumentList>\n"
           "    </action>\n"
           "    <action><name>Seek</name>\n"
           "      <argumentList>\n"
           "        <argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>\n"
           "        <argument><name>Unit</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_SeekMode</relatedStateVariable></argument>\n"
           "        <argument><name>Target</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_SeekTarget</relatedStateVariable></argument>\n"
           "      </argumentList>\n"
           "    </action>\n"
           "    <action><name>GetTransportInfo</name>\n"
           "      <argumentList>\n"
           "        <argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>\n"
           "        <argument><name>CurrentTransportState</name><direction>out</direction><relatedStateVariable>TransportState</relatedStateVariable></argument>\n"
           "        <argument><name>CurrentTransportStatus</name><direction>out</direction><relatedStateVariable>TransportStatus</relatedStateVariable></argument>\n"
           "        <argument><name>CurrentSpeed</name><direction>out</direction><relatedStateVariable>TransportPlaySpeed</relatedStateVariable></argument>\n"
           "      </argumentList>\n"
           "    </action>\n"
           "    <action><name>GetPositionInfo</name>\n"
           "      <argumentList>\n"
           "        <argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>\n"
           "        <argument><name>Track</name><direction>out</direction><relatedStateVariable>CurrentTrack</relatedStateVariable></argument>\n"
           "        <argument><name>TrackDuration</name><direction>out</direction><relatedStateVariable>CurrentTrackDuration</relatedStateVariable></argument>\n"
           "        <argument><name>TrackMetaData</name><direction>out</direction><relatedStateVariable>CurrentTrackMetaData</relatedStateVariable></argument>\n"
           "        <argument><name>TrackURI</name><direction>out</direction><relatedStateVariable>CurrentTrackURI</relatedStateVariable></argument>\n"
           "        <argument><name>RelTime</name><direction>out</direction><relatedStateVariable>RelativeTimePosition</relatedStateVariable></argument>\n"
           "        <argument><name>AbsTime</name><direction>out</direction><relatedStateVariable>AbsoluteTimePosition</relatedStateVariable></argument>\n"
           "        <argument><name>RelCount</name><direction>out</direction><relatedStateVariable>RelativeCounterPosition</relatedStateVariable></argument>\n"
           "        <argument><name>AbsCount</name><direction>out</direction><relatedStateVariable>AbsoluteCounterPosition</relatedStateVariable></argument>\n"
           "      </argumentList>\n"
           "    </action>\n"
           "    <action><name>GetCurrentTransportActions</name>\n"
           "      <argumentList>\n"
           "        <argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>\n"
           "        <argument><name>Actions</name><direction>out</direction><relatedStateVariable>CurrentTransportActions</relatedStateVariable></argument>\n"
           "      </argumentList>\n"
           "    </action>\n"
           "    <action><name>GetMediaInfo</name>\n"
           "      <argumentList>\n"
           "        <argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>\n"
           "        <argument><name>NrTracks</name><direction>out</direction><relatedStateVariable>NumberOfTracks</relatedStateVariable></argument>\n"
           "        <argument><name>MediaDuration</name><direction>out</direction><relatedStateVariable>CurrentMediaDuration</relatedStateVariable></argument>\n"
           "        <argument><name>CurrentURI</name><direction>out</direction><relatedStateVariable>AVTransportURI</relatedStateVariable></argument>\n"
           "        <argument><name>CurrentURIMetaData</name><direction>out</direction><relatedStateVariable>AVTransportURIMetaData</relatedStateVariable></argument>\n"
           "        <argument><name>NextURI</name><direction>out</direction><relatedStateVariable>NextAVTransportURI</relatedStateVariable></argument>\n"
           "        <argument><name>NextURIMetaData</name><direction>out</direction><relatedStateVariable>NextAVTransportURIMetaData</relatedStateVariable></argument>\n"
           "        <argument><name>PlayMedium</name><direction>out</direction><relatedStateVariable>PlaybackStorageMedium</relatedStateVariable></argument>\n"
           "        <argument><name>RecordMedium</name><direction>out</direction><relatedStateVariable>RecordStorageMedium</relatedStateVariable></argument>\n"
           "        <argument><name>WriteStatus</name><direction>out</direction><relatedStateVariable>RecordMediumWriteStatus</relatedStateVariable></argument>\n"
           "      </argumentList>\n"
           "    </action>\n"
           "  </actionList>\n"
           "  <serviceStateTable>\n"
           "    <stateVariable sendEvents=\"yes\"><name>LastChange</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable><name>TransportState</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable><name>TransportStatus</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable><name>TransportPlaySpeed</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable><name>AVTransportURI</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable><name>AVTransportURIMetaData</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable><name>NextAVTransportURI</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable><name>NextAVTransportURIMetaData</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable><name>CurrentTrack</name><dataType>ui4</dataType></stateVariable>\n"
           "    <stateVariable><name>CurrentTrackDuration</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable><name>CurrentTrackMetaData</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable><name>CurrentTrackURI</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable><name>RelativeTimePosition</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable><name>AbsoluteTimePosition</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable><name>RelativeCounterPosition</name><dataType>i4</dataType></stateVariable>\n"
           "    <stateVariable><name>AbsoluteCounterPosition</name><dataType>i4</dataType></stateVariable>\n"
           "    <stateVariable><name>CurrentMediaDuration</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable><name>NumberOfTracks</name><dataType>ui4</dataType></stateVariable>\n"
           "    <stateVariable><name>PlaybackStorageMedium</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable><name>RecordStorageMedium</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable><name>RecordMediumWriteStatus</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable><name>A_ARG_TYPE_InstanceID</name><dataType>ui4</dataType></stateVariable>\n"
           "    <stateVariable><name>A_ARG_TYPE_SeekMode</name><dataType>string</dataType><allowedValueList><allowedValue>REL_TIME</allowedValue><allowedValue>ABS_TIME</allowedValue></allowedValueList></stateVariable>\n"
           "    <stateVariable><name>A_ARG_TYPE_SeekTarget</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable><name>CurrentTransportActions</name><dataType>string</dataType></stateVariable>\n"
           "  </serviceStateTable>\n"
           "</scpd>";
}

const char* rcSCPDXML() {
    return "<?xml version=\"1.0\"?>\n"
           "<scpd xmlns=\"urn:schemas-upnp-org:service-1-0\">\n"
           "  <specVersion><major>1</major><minor>0</minor></specVersion>\n"
           "  <actionList>\n"
           "    <action><name>GetVolume</name>\n"
           "      <argumentList>\n"
           "        <argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>\n"
           "        <argument><name>Channel</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_Channel</relatedStateVariable></argument>\n"
           "        <argument><name>CurrentVolume</name><direction>out</direction><relatedStateVariable>Volume</relatedStateVariable></argument>\n"
           "      </argumentList>\n"
           "    </action>\n"
           "    <action><name>SetVolume</name>\n"
           "      <argumentList>\n"
           "        <argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>\n"
           "        <argument><name>Channel</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_Channel</relatedStateVariable></argument>\n"
           "        <argument><name>DesiredVolume</name><direction>in</direction><relatedStateVariable>Volume</relatedStateVariable></argument>\n"
           "      </argumentList>\n"
           "    </action>\n"
           "    <action><name>GetMute</name>\n"
           "      <argumentList>\n"
           "        <argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>\n"
           "        <argument><name>Channel</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_Channel</relatedStateVariable></argument>\n"
           "        <argument><name>CurrentMute</name><direction>out</direction><relatedStateVariable>Mute</relatedStateVariable></argument>\n"
           "      </argumentList>\n"
           "    </action>\n"
           "    <action><name>SetMute</name>\n"
           "      <argumentList>\n"
           "        <argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>\n"
           "        <argument><name>Channel</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_Channel</relatedStateVariable></argument>\n"
           "        <argument><name>DesiredMute</name><direction>in</direction><relatedStateVariable>Mute</relatedStateVariable></argument>\n"
           "      </argumentList>\n"
           "    </action>\n"
           "    <action><name>ListPresets</name>\n"
           "      <argumentList>\n"
           "        <argument><name>InstanceID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_InstanceID</relatedStateVariable></argument>\n"
           "        <argument><name>CurrentPresetNameList</name><direction>out</direction><relatedStateVariable>PresetNameList</relatedStateVariable></argument>\n"
           "      </argumentList>\n"
           "    </action>\n"
           "  </actionList>\n"
           "  <serviceStateTable>\n"
           "    <stateVariable sendEvents=\"yes\"><name>LastChange</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable><name>PresetNameList</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable><name>Volume</name><dataType>ui2</dataType><allowedValueRange><minimum>0</minimum><maximum>100</maximum><step>1</step></allowedValueRange></stateVariable>\n"
           "    <stateVariable><name>Mute</name><dataType>boolean</dataType></stateVariable>\n"
           "    <stateVariable><name>A_ARG_TYPE_InstanceID</name><dataType>ui4</dataType></stateVariable>\n"
           "    <stateVariable><name>A_ARG_TYPE_Channel</name><dataType>string</dataType><allowedValueList><allowedValue>Master</allowedValue></allowedValueList></stateVariable>\n"
           "  </serviceStateTable>\n"
           "</scpd>";
}

const char* cmSCPDXML() {
    return "<?xml version=\"1.0\"?>\n"
           "<scpd xmlns=\"urn:schemas-upnp-org:service-1-0\">\n"
           "  <specVersion><major>1</major><minor>0</minor></specVersion>\n"
           "  <actionList>\n"
           "    <action><name>GetProtocolInfo</name>\n"
           "      <argumentList>\n"
           "        <argument><name>Source</name><direction>out</direction><relatedStateVariable>SourceProtocolInfo</relatedStateVariable></argument>\n"
           "        <argument><name>Sink</name><direction>out</direction><relatedStateVariable>SinkProtocolInfo</relatedStateVariable></argument>\n"
           "      </argumentList>\n"
           "    </action>\n"
           "    <action><name>GetCurrentConnectionIDs</name>\n"
           "      <argumentList>\n"
           "        <argument><name>ConnectionIDs</name><direction>out</direction><relatedStateVariable>CurrentConnectionIDs</relatedStateVariable></argument>\n"
           "      </argumentList>\n"
           "    </action>\n"
           "    <action><name>GetCurrentConnectionInfo</name>\n"
           "      <argumentList>\n"
           "        <argument><name>ConnectionID</name><direction>in</direction><relatedStateVariable>A_ARG_TYPE_ConnectionID</relatedStateVariable></argument>\n"
           "        <argument><name>RcsID</name><direction>out</direction><relatedStateVariable>A_ARG_TYPE_RcsID</relatedStateVariable></argument>\n"
           "        <argument><name>AVTransportID</name><direction>out</direction><relatedStateVariable>A_ARG_TYPE_AVTransportID</relatedStateVariable></argument>\n"
           "        <argument><name>ProtocolInfo</name><direction>out</direction><relatedStateVariable>A_ARG_TYPE_ProtocolInfo</relatedStateVariable></argument>\n"
           "        <argument><name>PeerConnectionManager</name><direction>out</direction><relatedStateVariable>A_ARG_TYPE_ConnectionManager</relatedStateVariable></argument>\n"
           "        <argument><name>PeerConnectionID</name><direction>out</direction><relatedStateVariable>A_ARG_TYPE_ConnectionID</relatedStateVariable></argument>\n"
           "        <argument><name>Direction</name><direction>out</direction><relatedStateVariable>A_ARG_TYPE_Direction</relatedStateVariable></argument>\n"
           "        <argument><name>Status</name><direction>out</direction><relatedStateVariable>A_ARG_TYPE_ConnectionStatus</relatedStateVariable></argument>\n"
           "      </argumentList>\n"
           "    </action>\n"
           "  </actionList>\n"
           "  <serviceStateTable>\n"
           "    <stateVariable sendEvents=\"yes\"><name>SourceProtocolInfo</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable sendEvents=\"yes\"><name>SinkProtocolInfo</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable sendEvents=\"yes\"><name>CurrentConnectionIDs</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable><name>A_ARG_TYPE_ConnectionStatus</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable><name>A_ARG_TYPE_ConnectionManager</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable><name>A_ARG_TYPE_Direction</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable><name>A_ARG_TYPE_ProtocolInfo</name><dataType>string</dataType></stateVariable>\n"
           "    <stateVariable><name>A_ARG_TYPE_ConnectionID</name><dataType>i4</dataType></stateVariable>\n"
           "    <stateVariable><name>A_ARG_TYPE_AVTransportID</name><dataType>i4</dataType></stateVariable>\n"
           "    <stateVariable><name>A_ARG_TYPE_RcsID</name><dataType>i4</dataType></stateVariable>\n"
           "  </serviceStateTable>\n"
           "</scpd>";
}
